server:
  port: 8080
  servlet:
    context-path: /tijian
logging:
  level:
    org.springframework: debug
    com.example.demoinii.mapper: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tijian?characterEncoding=utf-8
    username: root
    password: 123456

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.example.demoinii.po,com.example.demoinii.dto

logging.level.org.springframework.boot.autoconfigure: error
